### ISSUE TITLE
issue with update method 

### ISSUE THREAD

**Issue by karakol15** [LaunchpadAI/space-bandits#12]
I am able to create a model, but once I am trying to use update method (both linear and neural models) 
context = np.array([76, 120, 654326, 2])
action = 1
reward = 14
model.update(context, action, reward)

RuntimeError                              Traceback (most recent call last)
<ipython-input-26-673552a97039> in <module>
      8 
      9 #here we update the model:
---> 10 model.update(context, action, reward)

~\Desktop\space-bandits-master\space_bandits\linear.py in update(self, context, action, reward)
    209         """
    210         self.t += 1
--> 211         self.data_h.add(context, action, reward)
    212 
    213         self._update_action(action)

~\Desktop\space-bandits-master\space_bandits\contextual_dataset.py in add(self, context, action, reward)
     54         if self.intercept:
     55             c = context[:]
---> 56             c = torch.cat((c, torch.tensor([1.0]).double
     57             c = c.reshape((1, self.context_dim + 1))
     58         else:

RuntimeError: Expected object of scalar type Int but got scalar type Double for sequence elment 1 in sequence argument at position #1 'tensors'

**Comment by AlliedToasters** [comment]
@karakol15 , Thanks for the issue. I have made a fix and pushed a new release, v0.0.991. You should be able to install it with `pip install space-bandits==0.0.991`.

If you do not wish to update, you can fix the issue by making sure your context array contains floating point values, not integers (this was the source of the error.)

Let me know if the fix is working.

**Comment by karakol15** [comment]
@AlliedToasters thank  you very much for your response. I would like to clarify one more question, not sure if this is the typical behavior of the algorithms or I am having some issues. 
I am using the model in the following way: 
number of actions = 12 
context = 6 

I tested the model using my data and randomly generated data. 
from space_bandits import NeuralBandits
model_test = NeuralBandits(12, 6)

I this case , I am interested in to "observe" how the model is learning, so instead of fit method I use update method. Here is an example using random numbers. 

total = []
for i in range(400):
    context = np.random.random((5))
    action = np.random.randint(0, 12)
    reward = np.random.random() * 12
    model_test.update(context, action, reward)
    total.append(model_test.action(context))

Simple method for counting how many times each action was selected. 

from collections import Counter
counter=Counter(total)
kot =[list(counter.keys()),list(counter.values())]
pd.DataFrame(np.array(kot).T, columns=['Action','Times Selected'])


I had 400 updates - and what I see is that each action was selected 33 -34 times. So I can assume that Thompson Sampling is not working just with update method? 

I tried to increase the amount of entries to 600 and I got the same, each action was selected 50 times. 
When I increased the number to 900, I got the results  that look like that TS is working. Could you please explain this issue?

**Comment by LanaBond77** [comment]
@karakol15, I have similar issue, is it possible to use the model just with update method?

**Comment by AlliedToasters** [comment]
Original issue is fixed in latest release, please reinstall if you are still experiencing the issue and post traceback if it persists.

Regarding action counts, @karakol15 , this is default behavior - the model is doing initial exploration. This is a very common heuristic in bandit models. Before making predictions, the model cycles through all available actions uniformly. To disable this, pass initial_pulls=0 to the constructor. The default parameter is 50, which means 50 pulls per action before the model begins to use Thompson sampling.

**Comment by karakol15** [comment]
@AlliedToasters thank you very much for your explanation. This is really interesting project
